//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.06 at 11:45:49 odp. CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mff.cuni.cz/~peckam/java/origamist/common/")
package cz.cuni.mff.peckam.java.origamist.common.jaxb;
