//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.27 at 06:31:40 dop. CEST 
//


package cz.cuni.mff.peckam.java.origamist.common.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Provided property: generated
 * <p>Java class for Thumbnail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Thumbnail">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.mff.cuni.cz/~peckam/java/origamist/common/v1}Image">
 *       &lt;attribute name="generated" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlType(name = "Thumbnail")
@XmlAccessorType(XmlAccessType.PROPERTY)
public class Thumbnail
    extends Image
    implements Equals, HashCode
{

    protected Boolean generated;
    /**
     * Property generated
     * 
     */
    public final static String GENERATED_PROPERTY = "generated:cz.cuni.mff.peckam.java.origamist.common.jaxb.Thumbnail";

    public Thumbnail() {
        if (getClass().getName().equals("cz.cuni.mff.peckam.java.origamist.common.jaxb.Thumbnail")) {
            init();
        }
    }

    /**
     * Gets the value of the generated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isGenerated() {
        if (generated == null) {
            return true;
        } else {
            return generated;
        }
    }

    /**
     * Sets the value of the generated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @XmlAttribute
    public void setGenerated(Boolean value) {
        Boolean old = this.generated;
        this.generated = value;
        if (old!= value) {
            support.firePropertyChange(Thumbnail.GENERATED_PROPERTY, old, value);
        }
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Thumbnail)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final Thumbnail that = ((Thumbnail) object);
        {
            boolean lhsGenerated;
            lhsGenerated = this.isGenerated();
            boolean rhsGenerated;
            rhsGenerated = that.isGenerated();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "generated", lhsGenerated), LocatorUtils.property(thatLocator, "generated", rhsGenerated), lhsGenerated, rhsGenerated)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            boolean theGenerated;
            theGenerated = this.isGenerated();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "generated", theGenerated), currentHashCode, theGenerated);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
