//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.02 at 01:12:42 dop. CET 
//


package cz.cuni.mff.peckam.java.origamist.model.jaxb;

import java.awt.Color;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter1
    extends XmlAdapter<String, Color>
{


    public Color unmarshal(String value) {
        return (cz.cuni.mff.peckam.java.origamist.utils.ColorConverter.parse(value));
    }

    public String marshal(Color value) {
        return (cz.cuni.mff.peckam.java.origamist.utils.ColorConverter.print(value));
    }

}
