//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.22 at 04:43:03 odp. CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mff.cuni.cz/~peckam/java/origamist/diagram/")
package cz.cuni.mff.peckam.java.origamist.model.jaxb;
